on: [push]

jobs:
  push-test:
    runs-on: [codeberg-small, codeberg-tiny]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - shell: bash
        run: scripts/docker-test.sh
