# Ansible Role: google-service-account
# File: homelab/playbooks/roles/google-service-account/tasks/main.yml
- name: Minimal Service Account Setup
  tags: google-cloud
  block:
    - name: "Ensure required variables are set"
      ansible.builtin.assert:
        that:
          - service_account_file is defined and service_account_file | length > 0
          - service_account_name is defined and service_account_name | length > 0
          - google_cloud_project is defined and google_cloud_project | length > 0
        fail_msg: "One or more required variables are not set."

    - name: Set service account variables
      ansible.builtin.set_fact:
        service_account_dir: "{{ service_account_file | dirname }}"
        service_account_file_name: "{{ service_account_file | basename }}"
        service_account_email: "{{ service_account_name }}@{{ google_cloud_project }}.iam.gserviceaccount.com"
        service_account_src_dir: "{{ playbook_dir }}/../.vault/{{ role_path | basename }}"

    - name: Copy service account key file to target machine
      ansible.builtin.copy:
        src: "{{ service_account_src_dir }}/{{ service_account_file_name }}"
        dest: "{{ service_account_file }}"
        mode: '0600'
