.PHONY: ⚙️ 👨🏻‍🏫  # make all commands phony

# The "usage" targets will find all commands in the available Makefiles and generate a usage message as follows:
# - lines starting with '##' are section headers
# - comments with '##' on the same line as a target are used as descriptions for the commands
# - command names are colored, descriptions are in normal text and indented
# - at the end of a section, a separator line is printed and the file name of the command is printed

SHELL = bash

USAGE_EXTRA ?= \
\n    -B   rebuild even if file exists\
\n    -n   dry run (prints target instead of running it)\n\

USAGE_ARGS ?= [-n|-B] VAR1=val VAR2=val

usage: 👨🏻‍🏫  ## show help for all documented targets in all loaded Makefiles
	@awk -v fmt="\nUsage: make %s %s\n" \
		 -v all='$(USAGE_ALL)' \
		 -v extra='$(USAGE_EXTRA)' \
	     -v trg='[target]' \
		 -v args='$(USAGE_ARGS)' -F ':.*##' \
	     'function blu(text)          { return "\033[36m" text "\033[0m"; } \
		  function gry(text)          { return "\033[90m" text "\033[0m"; } \
		  BEGIN                       { printf fmt, blu(trg), blu(args); prev=""; print extra } \
          FILENAME ~ "usage.mk"       { nextfile } \
		  FILENAME != "Makefile" && !all { exit 0 } \
		  FILENAME != prev       &&  all { printf gry("\n---- " FILENAME " ----\n"); prev=FILENAME } \
	      /^[a-zA-Z0-9! _-]+%?:.*?##/ { printf "    %-24s %s\n", blu($$1), $$2 } \
		  /^## [a-zA-Z0-9]+.*/        { printf "\n  %s\n", substr($$0, 4) } \
		  END                         { printf "\n" gry("---- help generated by usage.mk ----") "\n" }' \
		  $(MAKEFILE_LIST)

usage-all: USAGE_ALL=1
usage-all: 👨🏻‍🏫 usage

# How to generate Makefile.md with proper formatting?
# 1. Run 'make usage-all' to get all commands with descriptions
# 2. Clean up the output to make it suitable for markdown:
#    - Replace 'Usage: make [target] [args]' with '# Usage'
#    - Replace command names with backticks for code formatting
#    - Replace section headers with markdown headers (##)
#    - Replace separator lines with horizontal rules (---)
#    - Remove ANSI color codes
# 3. Redirect the cleaned output to Makefile.md
Makefile.md: 👨🏻‍🏫  ## generate Makefile documentation by running 'make help'
	echo '# Usage' > $@
	echo '> 🤖 DO NOT EDIT THIS FILE MANUALLY! \' >> $@
	echo '> This file is auto-generated by the command `make $@`.' >> $@
	@awk -F ':.*##' \
		 'function strip_ansi(text) { gsub(/\033\[[0-9;]*m/, "", text); return text } \
		  /^Usage: make/            { print "```sh\n" strip_ansi($$0) "\n```\n" } \
		  /^[a-zA-Z0-9! _-]+%?:.*?##/ { printf "- `%s`: %s\n", strip_ansi($$1), strip_ansi($$2) } \
		  /^## [a-zA-Z0-9]+.*/      { printf "\n## %s\n", substr(strip_ansi($$0), 4) } \
		  /^---- .* ----/           { print "\n---\n" }' \
		  $(MAKEFILE_LIST) >> $@
	@echo "Generated $@"
