.PHONY: 👨🏻‍🏫 ⚙️

SHELL = bash

USAGE_EXTRA ?= \n \
\   -B    rebuild even if file exists \n \
\   -n    dry run (prints target instead of running it) \n

USAGE_ARGS ?= [-n|-B] VAR1=val VAR2=val

usage-all: USAGE_ALL=1
usage-all: 👨🏻‍🏫 usage

usage: 👨🏻‍🏫  ## show help for all documented targets in all loaded Makefiles
	@awk -v fmt="\nUsage: make %s %s\n" \
		 -v all='$(USAGE_ALL)' \
		 -v extra='$(USAGE_EXTRA)' \
	     -v trg='[target]' \
		 -v args='$(USAGE_ARGS)' -F ':.*##' \
	     'function blu(text)          { return "\033[36m" text "\033[0m"; } \
		  function gry(text)          { return "\033[90m" text "\033[0m"; } \
		  BEGIN                       { printf fmt, blu(trg), blu(args); prev=""; print extra } \
          FILENAME ~ "usage.mk"       { nextfile } \
		  FILENAME != "Makefile" && !all { exit 0 } \
		  FILENAME != prev       &&  all { printf gry("\n---- " FILENAME " ----\n"); prev=FILENAME } \
	      /^[a-zA-Z0-9! _-]+%?:.*?##/ { printf "    %-24s %s\n", blu($$1), $$2 } \
		  /^## [a-zA-Z0-9]+.*/        { printf "\n  %s\n", substr($$0, 4) } \
		  END                         { printf "\n" gry("---- help generated by usage.mk ----") "\n" }' \
		  $(MAKEFILE_LIST)